<?php
/**
 * InfinityFab Lab Scheduler Module
 *
 * Developed for the Infinity Fab Lab at the University of Florida.
 * Features:
 *  - frontend scheduler interface, using Adam Shaw's FullCalendar javascript calendar
 *  - reservation pagetype, which represents a single equipment reservation
 *  - equipment pagetype, which represents a single piece of reservable equipment
 *  - rule pagetype, which represents a set of rules according to which a piece of equipment may be reserved
 *  - backend interface for managing reservations and equipment, using ProcessPageTypes
 *  - fully configurable in terms
 *
 * Thomas R Storey, 2015
 * Licensed under MIT License, see LICENSE.TXT
 *
 * http://fablab.arts.ufl.edu
 * https://github.com/UF-Asq-Fab-Lab
 * sudo rm -R /var/www/html/sandbox/fablab/site/modules/LabUser && sudo cp ~/projects/fablab/LabUser /var/www/html/sandbox/fablab/site/modules/LabUser
 */

class LabScheduler extends WireData implements Module, ConfigurableModule {

  /**
   * Return information about the module
   *
   */
  static public function getModuleInfo() {
    return array(
      'title' => 'Lab Equipment Scheduler',
      'version' => 100,
      'summary' => 'Allows frontend users to reserve equipment through a calendar interface according to a set of rules assigned to each piece of equipment',
      'author' => 'Thomas R Storey',
      'autoload' => true,
      'singular' => true,
      'installs' => array(
        'ProcessLabTool',
        'ProcessLabReservation',
        'ProcessLabEquipmentRule'
      ),
      'requires' => array('FabLabModuleHelpers')
      );
  }
  const LabReservationTemplateName = 'lab_reservation';
  const LabToolTemplateName = 'lab_tool';
  const LabRulesetTemplateName = 'lab_ruleset';

  protected $initialized = false;

  public function __construct() {
    $this->set('initialized', false);
    //load classes
    $dirname = dirname(__FILE__);
		require_once($dirname . '/LabReservation.php');
    require_once($dirname . '/LabReservations.php');
    require_once($dirname . '/LabTool.php');
    require_once($dirname . '/LabTools.php');
    require_once($dirname . '/LabRuleset.php');
    require_once($dirname . '/LabRulesets.php');
    //set config placeholders
    $this->set('labReservationsPageID', 0);
    $this->set('labToolsPageID', 0);
    $this->set('labRulesetsPageID', 0);
  }

  public function init() {
    // prevent possible double init
		if($this->initialized) return;
		$this->initialized = true;

    $this->data = wire('modules')->getModuleConfigData($this);
    $this->schedulePageID = $this->data['lab_schedule_id'];
    $this->helper = $this->wire('modules')->get('FabLabModuleHelpers');

    // create $lab_reservations API variable.
    $labReservationTemplate = $this->templates->get(self::LabReservationTemplateName);
    if(!$labReservationTemplate) return;
    if(!$this->labReservationsPageID){
      $selector = 'template=admin, process=ProcessLabReservation, name=lab_reservations';
      $lrp = $this->wire('pages')->get($selector);
      $this->labReservationsPageID = $lrp->id;
    }
    $lab_reservations = new LabReservations($labReservationTemplate, $this->labReservationsPageID);
    $this->wire('lab_charges', $lab_charges);

    // create $lab_tools API variable.
    $labToolTemplate = $this->templates->get(self::LabToolTemplateName);
    if(!$labToolTemplate) return;
    if(!$this->labToolsPageID){
      $selector = 'template=admin, process=ProcessLabTool, name=lab_tools';
      $lcip = $this->wire('pages')->get($selector);
      $this->labToolsPageID = $lcip->id;
    }
    $lab_tools = new LabTools($labToolTemplate, $this->labToolsPageID);
    $this->wire('lab_tools', $lab_tools);
    $this->response = array();
  }

  public function ready () {
    if($this->wire('config')->ajax){
      return $this->handleAjaxRequests();
    }
    if($this->wire('page')->id == $this->schedulerPageID){
      if($post = $this->wire('input')->post){
        if($post->reserve){
          $this->handleCreateReservation();
        }
        if($post->cancel){
          $this->handleCancelReservation($this->wire('input')->post);
        }
      }
      // add styles and scripts to scheduler page
      $liburl = wire('config')->urls->siteModules.'/LabScheduler/lib/';
      $incurl = wire('config')->urls->siteModules.'/LabScheduler/includes/';
      $this->wire('config')->styles->add($liburl."css/fullcalendar.css");
      $this->wire('config')->styles->add($liburl."css/scheduler.css");
      $this->wire('config')->styles->add($incurl."css/labScheduler.css");

      $this->wire('config')->scripts->add($liburl."js/moment.min.js");
      $this->wire('config')->scripts->add($liburl."js/fullcalendar.js");
      $this->wire('config')->scripts->add($liburl."js/scheduler.js");
      $this->wire('config')->scripts->add($incurl."js/labScheduler.js");
      // hook to template render
      $this->addHookAfter('TemplateFile::render', $this, 'hookRenderSchedule');
    }
  }

  protected function hookRenderSchedule(HookEvent $event){
    // render schedule to string.
    $incurl = wire('config')->urls->siteModules.'/LabScheduler/includes/';
    $path = $incurl."/labSchedule.inc";
    $res .= $this->helper->renderFileToString($path);
    $event->return = str_replace("[schedule]", $res, $event->return);
  }

  protected function handleCreateReservation(){
    $input = $this->wire('input');
    if($input->post('reservation-submit')){
      if($this->validateReservation()){
        $res = new LabReservation();
        $username = $this->wire('user')->name;
        $tool = $input->post->text('reservation-tool');
        $startDate = $input->post->text("reservation-start-date");
        $startTime = $input->post->text('reservation-start-time');
        $endDate = $input->post->text("reservation-end-date");
        $endTime = $input->post->text('reservation-end-time');
        $res->title = sprintf("%s %s %s %s", $username, $tool, $startDate, $startTime);
        $res->lab_reservation_start = $startDate." ".$startTime;
        $res->lab_reservation_end = $endDate." ".$endTime;
        $res->lab_reservation_tool = $this->wire('lab_tools')->get('name='.$tool);
        $res->lab_reservation_user = $this->wire('user');
        $res->save();
        $this->response[] = "<p class='message'>Reservation successful!</p>"
      } else {
        $invalidMsg = "<p class='error'>Invalid reservation. Please see the";
        $invalidMsg .= " messages below and adjust your reservation as";
        $invalidMsg .= " necessary, then try again.</p>";
        array_unshift($this->response, $invalidMsg);
      }
    }
  }

  protected function handleCancelReservation(){
    $input = $this->wire('input');
    if($input->post('reservation-cancel-submit')){
      if($this->validateCancellation()){
        $resID = $input->post->text('reservation-cancel-id');
        $res = $this->wire('lab_reservations')->get($resID);
        $this->wire('lab_reservations')->delete($res, true);
        $this->response[] = "<p class='message'>Reservation cancelled.</p>";
      } else {
        $invalidMsg = "<p class='error'>Reservation cancellation failed.</p>";
        array_unshift($this->response, $invalidMsg);
      }
    }
  }

  protected function handleAjaxRequests(){
    if(wire('config')->ajax && wire('input')->get('reservations')){
      $this->addHookBefore('TemplateFile::render', $this, 'hookAjaxGetReservations');
    }
    if(wire('config')->ajax && wire('input')->get->('tools')){
      $this->addHookBefore('TemplateFile::render', $this, 'hookAjaxGetTools');
    }
  }

  protected function hookGetEvents(HookEvent $event){
    $input = $this->wire('input');
    $startTimestamp = strtotime($input->get->text('start'));
    $endTimestamp = strtotime($input->get->text('end'));
    $json = array(
      'events' => array(),
      'resources' => array()
    );
    $selector = "lab_reservation_start>=$startTimestamp, ";
    $selector.= "lab_reservation_end<=$endTimestamp, ";
    $selector.= "check_access=0, include=all";
    $reservations = $this->wire('lab_reservations')->find($selector);
    foreach($reservations as $res){
      $json['events'][] = array(
        'title' => $res->title,
        'start' => $res->lab_reservation_start,
        'end' => $res->lab_reservation_end,
        'resourceId' => $res->lab_reservation->tool->id,
        'id' => $res->id
      );
    }

    

  }

  protected function hookGetConfig(HookEvent $event){

  }

  protected function renderReservationsJSON($start, $end){

  }

  protected function renderConfigJSON(){

  }

  protected function validateReservation($postdata){
    $dateStartStr = $input->post('reservation-start-date');
    $timeStartStr = $input->post('reservation-start-time');
    $dateTimeStart = new DateTime($dateStartStr." ".$timeStartStr);
    $dateEndStr = $input->post('reservation-end-date');
    $timeEndStr = $input->post('reservation-end-time');
    $dateTimeEnd = new DateTime($dateEndStr." ".$timeEndStr);
  }

  protected function validateCancellation($postdata){

  }

  protected function evaluateRuleset($start, $end, $user, $tool, $ruleset){

  }

  protected function isValidDay($start, $end, $rule){

  }

  protected function isValidHour($start, $end, $rule){

  }

  protected function isValidToolUsagePerWeek($start, $end, $tool, $rule){

  }

  protected function isValidCancelUser($start, $end, $rule){

  }

  protected function isValidOverlap($start, $end, $rule){

  }

  protected function isValidTotalUsagePerWeek($start, $end, $rule){

  }

  protected function isValidLength($start, $end, $rule){

  }

  protected function isValidBuffer($start, $end, $rule){

  }

  protected function installer($install = true) {
		require_once($this->config->paths->LabScheduler . 'LabSchedulerInstall.php');
		$installer = new LabSchedulerInstall();
		if($install) $installer->install();
			else $installer->uninstall();
	}

  public function install () {
    $this->installer(true);
  }

  public function uninstall () {
    $this->installer(false);
  }

}

?>
