<?php

/**
 * Infinity Fab Lab Charge Process Module
 *
 * Developed for the Infinity Fab Lab at the University of Florida.
 * Lists and allows adding and editing Lab Charge pages.
 *
 * Thomas R Storey, 2015
 * Licensed under MIT License, see LICENSE.TXT
 *
 * http://fablab.arts.ufl.edu
 * https://github.com/UF-Asq-Fab-Lab
 */

class ProcessLabRuleset extends ProcessPageType {

	static public function getModuleInfo() {
		return array(
			'title'      => __('Lab Rulesets', __FILE__), // getModuleInfo title
			'version'    => 100,
			'summary'    => __('Manage lab rulesets', __FILE__), // getModuleInfo summary
			'permission' => 'user-admin',
			'icon'       => 'gavel',
      'requires'   => array('LabScheduler'),
			'permission' => 'scheduler-edit',
			'useNavJSON' => true,
		);
	}

	public function __construct() {
		$this->set("maxAjaxQty", 25);
		return parent::__construct();
    $showFields = array(
      'title',
      'lab_ruleset_roles'
    );
		$this->set('showFields', $showFields);
	}

	public function init() {
		parent::init();
		$this->addHookAfter('ProcessPageAdd::buildForm', $this, 'hookAfterPageAddBuildForm');

	}

	protected function useLister() {
		return true;
	}

	public function ___executeEdit() {
		$out = parent::___executeEdit();
		return $out;
	}

	protected function hookAfterPageAddBuildForm(HookEvent $event){
		$form = $event->return;
		$formSave = $form->children('name=submit_save')->first();
		// roles
		$field = $this->wire('fields')->get('lab_ruleset_roles')->getInputfield(new NullPage());
		$field->value = "user";
		$form->insertBefore($field, $formSave);
		// hours per week
		$field = $this->wire('fields')->get('lab_ruleset_hours_per_week')->getInputfield(new NullPage());
		$field->value = 10;
		$form->insertBefore($field, $formSave);
		// reserve buffer
		$field = $this->wire('fields')->get('lab_ruleset_reservation_buffer_hours')->getInputfield(new NullPage());
		$field->value = 6;
		$form->insertBefore($field, $formSave);
		// cancel buffer
		$field = $this->wire('fields')->get('lab_ruleset_cancellation_buffer_hours')->getInputfield(new NullPage());
		$field->value = 6;
		$form->insertBefore($field, $formSave);

		$field = $this->wire('fields')->get('lab_ruleset_minimum_reservation_hours')->getInputfield(new NullPage());
		$field->value = 1;
		$form->insertBefore($field, $formSave);

		$field = $this->wire('fields')->get('lab_ruleset_maximum_reservation_hours')->getInputfield(new NullPage());
		$field->value = 3;
		$form->insertBefore($field, $formSave);

		$field = $this->wire('fields')->get('lab_ruleset_reservable_days')->getInputfield(new NullPage());
		$field->value = "2,3,4,5,6";
		$form->insertBefore($field, $formSave);

		$field = $this->wire('fields')->get('lab_ruleset_reservable_hours')->getInputfield(new NullPage());
		$field->value = "8,9,10,11,12,13,14,15,16,17,18";
		$form->insertBefore($field, $formSave);

		$event->return = $form;
	}
}
?>
